openapi: "3.1.0"
info:
  title: "hris_backend API"
  description: "hris_backend API"
  version: "1.0.0"
servers:
- url: "https://hris_backend"
paths:
  /metrics:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"