openapi: "3.1.0"
info:
  title: "Notifications service API"
  description: "Notifications service API"
  version: "0.0.1"
servers:
- url: "https://localhost:8083"
paths:
  /metrics:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"