version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: hris
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Start#123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  postgres-exporter:
    image: wrouesnel/postgres_exporter:latest
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:Start#123@postgres:5432/hris?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - postgres

  flyway:
    image: flyway/flyway:9.16.1
    container_name: flyway
    depends_on:
      - postgres
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/hris
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: Start#123
    volumes:
      - ./db/migration:/flyway/sql
    #command: -connectRetries=60 -cleanDisabled=false clean migrate
    command: -connectRetries=60 migrate

  employees-service:
    build:
      context: .
      dockerfile: employees/Dockerfile
    container_name: employee-service
    environment:
      DATABASE_URL: "jdbc:postgresql://postgres:5432/hris"
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: "Start#123"
    ports:
      - "8081:8081"
    depends_on:
      - flyway

  notifications-service:
    build:
      context: .
      dockerfile: notifications/Dockerfile
    container_name: notification-service
    environment:
      DATABASE_URL: "jdbc:postgresql://postgres:5432/hris"
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: "Start#123"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "8082:8082"
    depends_on:
      - flyway
      - postgres
      - rabbitmq

  rabbit-consumer-service:
    build:
      context: .
      dockerfile: rabbit-consumer/Dockerfile
    container_name: rabbit-consumer-service
    environment:
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "8084:8084"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"

  reviews-service:
    build:
      context: .
      dockerfile: reviews/Dockerfile
    container_name: review-service
    environment:
      DATABASE_URL: "jdbc:postgresql://postgres:5432/hris"
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: "Start#123"
    ports:
      - "8083:8083"
    depends_on:
      - flyway

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - employees-service
      - notifications-service
      - reviews-service

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  pgdata:
