### Получить список всех ревью
GET http://localhost:8083/performance_reviews
Accept: application/json

### Создать новое ревью
POST http://localhost:8083/performance_reviews
Content-Type: application/json

{
  "employeeId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
  "teamId": "11111111-1111-1111-1111-111111111111",
  "reviewDate": "2025-02-15",
  "performance": 8,
  "softSkills": 7,
  "independence": 9,
  "aspirationForGrowth": 8
}

### Получить ревью по ID
GET http://localhost:8083/performance_reviews/{id}
Accept: application/json

### Обновить ревью по ID
PUT http://localhost:8083/performance_reviews/{id}
Content-Type: application/json

{
  "employeeId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
  "teamId": "11111111-1111-1111-1111-111111111111",
  "reviewDate": "2025-02-15",
  "performance": 9,
  "softSkills": 8,
  "independence": 10,
  "aspirationForGrowth": 9
}

### Удалить ревью по ID
DELETE http://localhost:8083/performance_reviews/{id}

### Получить ревью для сотрудника
GET http://localhost:8083/performance_reviews/employee/{employeeId}
Accept: application/json

### Получить ревью с пагинацией
GET http://localhost:8083/performance_reviews/paginated?sortBy=reviewDate&order=asc&page=1&pageSize=20
Accept: application/json
