### Получение списка всех сотрудников
GET http://localhost:8081/employees
Accept: application/json


### Создание нового сотрудника
POST http://localhost:8081/employees
Content-Type: application/json

{
  "firstName": "petd4ya12d23",
  "teamId": "15f3868a-82b3-468f-aa14-81d9bd500658",
  "lastName": "Doe1ds24f",
  "email": "pedtyda412432.doe1@example.com",
  "position": "Developer",
  "supervisorId": null
}


### Получение сотрудника по ID
GET http://localhost:8081/employees/f0c65528-8b0a-4855-9959-d4ac667c500e
Accept: application/json


### Обновление данных сотрудника
PUT http://localhost:8081/employees/f0c65528-8b0a-4855-9959-d4ac667c500e
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Doe",
  "email": "jane.doe@example.com",
  "position": "Senior Developer",
  "supervisorId": null
}


### Удаление сотрудника
DELETE http://localhost:8081/employees/f0c65528-8b0a-4855-9959-d4ac667c500e
Accept: application/json
