### Получение списка всех сотрудников
GET http://localhost:8081/employees
Accept: application/json

### Сортировка, пагинация
GET http://localhost:8081/employees/paginated?order=desc&page=1&pageSize=2
Accept: application/json

### Создание нового сотрудника
POST http://localhost:8081/employees
Content-Type: application/json

{
  "firstName": "petd4yfa12d7823",
  "teamId": "11111111-1111-1111-1111-111111111111",
  "lastName": "Doe1ds2f4f",
  "email": "pedtyda4g7g12432.doe1@example.com",
  "position": "Developer",
  "joiningDate": "2022-05-10",
  "supervisorId": null
}


### Получение сотрудника по ID
GET http://localhost:8081/employees/f0c65528-8b0a-4855-9959-d4ac667c500e
Accept: application/json


### Обновление данных сотрудника
PUT http://localhost:8081/employees/bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb
Content-Type: application/json

{
  "firstName": "Jane",
  "teamId": "15f3868a-82b3-468f-aa14-81d9bd500658",
  "lastName": "Doe",
  "email": "jane.doe@example.com",
  "position": "Senior Developer",
  "supervisorId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"
}


### Удаление сотрудника
DELETE http://localhost:8081/employees/f0c65528-8b0a-4855-9959-d4ac667c500e
Accept: application/json
